#! /bin/sh
DIR="/dev/tty$1"          #/dev/ttyUSB0 哪一个串口
SPEED=$2        #设置串口波特率
SearchStr=$3

sudo -s <<EOF #将EOF与 << 结合使用，表示后续的输入作为子命令或子Shell的输入，直到遇到EOF为止，再返回到主调Shell

#stty -F /dev/ttyUSB1 raw speed 921600 min 0 time 1 //设置串口的波特率和读取时间
stty -F $DIR raw speed $SPEED min 0 time 10

#while [ 1 -eq 1 ]
#do
    cat $DIR | grep -iE "$SearchStr" --color
#done
